[package]
name = "docs-se"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
description = "Docs Search Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
clap = "3.0.0-beta.5"
comrak = "0.12.1"
glob = "0.3.0"
rusqlite = "0.26.1"
serde = "1.0.130"
serde_json = "1.0.69"
serde_yaml = "0.8.21"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
uuid = { version = "0.8.2", features = ["v4"] }
