[package]
name = "docs-se"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
comrak = "0.12.1"
rusqlite = "0.26.1"
serde = "1.0.130"
serde_json = "1.0.69"
serde_yaml = "0.8.21"
